# Quiz 5 - Clustering

In [9]:
import pandas as pd
import numpy as np
import sys

sys.path.append("..")

from AI_algorithms.ml.unsupervised import KMeans
from AI_algorithms.utils.data import parse_table

In [10]:
data = '''
id	x0	x1	x2
0	0	0	1
1	1	0	0
2	1	1	1
3	1	1	0
4	0	0	0
5	0	1	1
'''
centroids = np.array([
    [0.79, 0.21, 0.38],
    [0.81, 0.05, 0.06],
    [0.97, 0.42, 0.44]
])
df = parse_table(data, index="index", columns=True).astype(float)
df.head()

     x0   x1   x2
id
0   0.0  0.0  1.0
1   1.0  0.0  0.0
2   1.0  1.0  1.0
3   1.0  1.0  0.0
4   0.0  0.0  0.0

In [12]:
model = KMeans(n_clusters=3, max_iter=1, tol=1e-4)
model.fit(df.values, centroids = centroids, verbose=True)

Iteration 1
Distances:
      C1     C2     C3
0  1.026  1.242  1.196
1  0.482  0.205  0.609
2  1.026  1.350  0.807
3  0.901  0.971  0.729
4  0.901  0.814  1.145
5  1.278  1.563  1.261
Centroids:
C1:    0.000    0.000    1.000
C2:    0.500    0.000    0.000
C3:    0.667    1.000    0.667


Converged after 1 iterations.

In [13]:
y = model.predict(df.values)
df_ = df.copy()
df_["cluster"] = y
df_.head()

     x0   x1   x2  cluster
id
0   0.0  0.0  1.0        0
1   1.0  0.0  0.0        1
2   1.0  1.0  1.0        2
3   1.0  1.0  0.0        2
4   0.0  0.0  0.0        1